React Capstone Project: Rwanda Locations App
egichuhis/rwanda-locations pull request #5
Opened 2023-10-11 14:15 UTC by egichuhis

Hello, please review this PR.

Changes made:

- Fetch Rwanda locations data from API
- Display the Provinces and metrics on cards
- Fetch selected Province data from API
- Display the Districts in a List
- Show various count data in header
- Use Redux to fetch and store data
- Add tests for app
- Implement design given using Bootstrap
- Deploy website to this [Link](https://rwanda-locations.onrender.com/)

2023-10-11 16:07 UTC, iambenkis requested changes
#### Hi @egichuhis 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
You did a great job, keep up the good work 👍🏼

![giphy](https://user-images.githubusercontent.com/25227022/169391888-8dd8108f-0d42-4e54-87cc-a3f9fd392dbc.gif)


## Highlights

✔️ All tests are passing 
✔️ Use Redux 
✔️ The project is a single page application (SPA)

## Suggested changes

- [ ] Good job finalizing your React base application 👏  , Good documentation also however a professional README file should not have a broken link. Kindly remove the broken link attached to the logo image and provide a relevant image 👍  or you may also remove the image 👍 

![Capture1](https://github.com/egichuhis/rwanda-locations/assets/80458199/6370a248-0daa-4c39-bb27-3bd6c09de418)


- [ ] Hey, great job with the project, I admire your effort so far, You've done well. I just wanted to point out something concerning the filtering feature. As it's a requirement to add a filter functionality, so a user could filter by a book name (or other refrence 😄 ), I don't seem to see it working as intended. When a user searches for a province , it should show up what matches the search . Please, try to add this implementation to meet this part of the project requirement. 👍

![Capture](https://github.com/egichuhis/rwanda-locations/assets/80458199/51549141-a1d0-4b28-a44d-f3e6035922aa)

![Capture](https://github.com/egichuhis/rwanda-locations/assets/80458199/28728187-2edf-4855-8bfa-a59c5a646214)

- [ ] Kindly make sure the app has a navbar as the provided has a navbar that is going to help the user to navigate throughout the page 👍 (Eg: Logo,  back button , search button, hamburger button , etc 😄  )  

![Capture](https://github.com/egichuhis/rwanda-locations/assets/80458199/83963b73-5936-4fb0-a4f9-9e89884d65c8)

![Capture](https://github.com/egichuhis/rwanda-locations/assets/80458199/4faf4256-5329-4a02-811d-994c63efc596)

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-10-11 16:07 UTC, iambenkis commented on src/App.js
> +import Districts from './components/District/Districts';
- [ ] Keep doing the great job 🚀

2023-10-12 09:45 UTC, egichuhis commented
Thanks @iambenkis for noting that. Cheers!

2023-10-12 09:58 UTC, V-Blaze approved these changes
Hi @egichuhis 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Project deployed and working💯
-  Search featured works fine👍
-  Clean and well-structured code🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 10:00 UTC, merged